---
dist: trusty
language: node_js
node_js:
  - 8
  - 9
install: true
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - me@michaelkohler.info
addons:
  ssh_known_hosts: me.michaelkohler.info
before_deploy:
  - openssl aes-256-cbc -K $encrypted_d1b4660665e6_key -iv $encrypted_d1b4660665e6_iv -in travis_deploy_rsa.enc -out /tmp/travis_deploy_rsa -d
  - chmod 600 /tmp/travis_deploy_rsa
  - ssh-add /tmp/travis_deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
